"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var Manager_1 = require("./Manager");
var product = new Product_1.Product(1, "iphoneX", "Điện thoại", "500$", 14, "122334", "Điện thoại Iphone sản xuất tại Việt Nam");
var product1 = new Product_1.Product(2, "samsung", "Điện thoại", "1500$", 4, "122334", "Điện thoại Iphone sản xuất tại Việt Nam");
var product2 = new Product_1.Product(3, "vinSmart", "Điện thoại", "1200$", 11, "122334", "Điện thoại Iphone sản xuất tại Việt Nam");
var product3 = new Product_1.Product(4, "Daikin", "Điều hòa", "1400$", 3, "122334", "Điện thoại Iphone sản xuất tại Việt Nam");
var product4 = new Product_1.Product(5, "panasonic", "Tủ lạnh", "600$", 4, "122334", "Điện thoại Iphone sản xuất tại Việt Nam");
var productList = new Manager_1.Manager();
productList.addProduct(product);
productList.addProduct(product1);
productList.addProduct(product2);
productList.addProduct(product3);
productList.addProduct(product4);
productList.showProductList();
productList.showFindName("iphoneX");
productList.deleteProduct("Daikin");
productList.editProduct("iphoneX", "điện thoại chính hãng", "700$", 6, "còn hàng");
